@baseUrl = http://localhost:9999/auth

### ユーザー登録
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "username": "testuser",
    "email": "john@example.com",
    "password": "password123"
} 



### ログイン
POST {{baseUrl}}/signin
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "password123"   
} 

### リフレッシュトークンの生成
POST {{baseUrl}}/refresh-token
Content-Type: application/json

{
    "refreshToken": "b60aeebb03c1bbd0ee09eb599e0040f279ecaa528d42212375662a11aa533466"
}

### サインアウト
POST {{baseUrl}}/signout

